################################################################################ 
# 
#  MODULE NAME: marginCalc.properties 
# 
#  DESCRIPTION: Contains the required property value for margin calculator to
#               connect to GUI btoker
# 
#  MODIFICATION HISTORY 
# 
#    DATE      PROG. 
#  DD-MMM-YYYY INIT.   SIR    MODIFICATION DESCRIPTION 
#  ----------- ------- ------ -------------------------------------------------- 
#  30-OCT-2013 MASINHA 253590 Added property gui.mc.enable
################################################################################

# context name
java.naming.factory.initial = org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.user=guest

#local configuration

connectionfactory.connection = amqp://10.127.168.114:20001?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

queue.requestAddress =  PRISMA.MC


gui.mc.enable=true

