################################################################################ 
# 
#  MODULE NAME: marginCalcAPI.properties 
# 
#  DESCRIPTION: Contains the required property value for margin calculator to
#               connect to API btoker
# 
#  MODIFICATION HISTORY 
# 
#    DATE      PROG. 
#  DD-MMM-YYYY INIT.   SIR    MODIFICATION DESCRIPTION 
#  ----------- ------- ------ -------------------------------------------------- 
#  13-FEB-2014 PATHVIM 256187 Created   IRS: Relocate Margin Calculator API to ERS
#                                       channel 
################################################################################

# context name
java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jndi.PropertiesFileInitialContextFactory
jms.user=guest

connectionfactory.connection=amqp://10.127.168.114:20003?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

#queue.requestAddesss=request.MCAPI
#queue.responseAddress=response.ResponseQueue


queue.requestAddress_BOSLO_PRODUFOAAOPTIMUS=request_be.BOSLO_PRODUFOAAOPTIMUS
queue.responseAddress=response.BOSLO_PRODUFOAAOPTIMUS


api.mc.enable=true
