# context name

java.naming.factory.initial = org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.user=guest

#connectionfactory.connection = amqp://10.112.46.69:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN
connectionfactory.connection = amqp://10.127.168.114:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

#queue.TradeNotification_VCON=VCON_Account1

# Broadcast Queues
topic.TradeNotification_TRADEWEB=broadcast/broadcast.TWBXT_TWEB1FOAAPRODCLR.TradeNotification


# Request Queues
queue.requestAddress_TWBXT_TWEB1FOAAPRODCLR=request_be.TWBXT_TWEB1FOAAPRODCLR



# Queue for viewing response on qpid broker UI
queue.responseAddress=response.TWBXT_TWEB1FOAAPRODCLR