# context name

java.naming.factory.initial = org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.user=guest

#local configuration
connectionfactory.connection = amqp://10.127.168.114:20001?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN


# ABCFR_ABCFRALMMACC1 setup in teapi_broker_maintenance as TRADE_SERV_ACCOUNT=ABCFR_ABCFRALMMACC1
queue.requestAddress_TRADE_SERV=request_be.DBKFR_Accoun1_TradeServ


topic.TradeNotification_MARKITSERV=broadcast/broadcast.DBKFR.TradeNotification

topic.TradeNotification_response\ResponseQueue=broadcast/broadcast.trade_notification_TradeServ1
topic.TradeNotification_TradeServ2=broadcast/broadcast.trade_notification_TradeServ2
#topic.TradeNotification_MARKITSERV=broadcast/broadcast.trade_notification_TradeServ
queue.responseAddress=ResponseQueue


