# context name

java.naming.factory.initial = org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.user=guest

#connectionfactory.connection = amqp://10.112.46.69:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN
connectionfactory.connection = amqp://10.127.168.114:20002:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

#queue.TradeNotification_VCON=VCON_Account1

# Broadcast Queues
topic.TradeNotification_TRAIANA=broadcast/broadcast.TRAXT_TRAXTALTEAPROD.TradeNotification


# Request Queues
queue.requestAddress_TRAXT_TRAXTALTEAPROD=request_be.TRAXT_TRAXTALTEAPROD



# Queue for viewing response on qpid broker UI
queue.responseAddress=response.TRAXT_TRAXTALTEAPROD
