################################################################################ 
# 
#  MODULE NAME: FpmlAPIProperties.properties 
# 
#  DESCRIPTION: Contains the required property value to connect to FpML btoker
# 
#  MODIFICATION HISTORY 
# 
#    DATE      PROG. 
#  DD-MMM-YYYY INIT.   SIR    MODIFICATION DESCRIPTION 
#  ----------- ------- ------ -------------------------------------------------- 
#  30-OCT-2013 MASINHA 253590 Added property api.mc.enable
################################################################################
# context name


#local configuration

connectionfactory.connection=amqp://otc-clearing-test-smoke3-secondary-rhel-01.clearing-otc.dev.gcp.dbgcloud.io:20001?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.user=guest

# Broadcast Queues:
topic.TradeNotification_ZKBZG=broadcast/broadcast.ZKBZH.TradeNotification
topic.TradeNotificationNCM_ZXBZH=broadcast/broadcast.ZKBZH.TradeNotificationNCM

# Request Queues
queue.requestAddress_ZKBZH_MSERVMOPRD=request_be.ZKBZH_MSERVMOPRD

# Response Queue
queue.responseAddress=response.ZKBZH_MSERVMOPRD

api.mc.enable=