# context name

java.naming.factory.initial = org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory

#connectionfactory.connection = amqp://10.112.46.69:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN
connectionfactory.connection = amqp://otc-clearing-test-smoke3-secondary-rhel-01.clearing-otc.dev.gcp.dbgcloud.io:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

#queue.TradeNotification_VCON=VCON_Account1

# Broadcast Queues
topic.TradeNotification_MISXT=broadcast/broadcast.MSAXT_MSAXTALTSERVFXPD.TradeNotification



# Request Queues
queue.requestAddress_MSAXT_MSAXTALTSERVFXPD=request_be.MSAXT_MSAXTALTSERVFXPD



# Queue for viewing response on qpid broker UI
queue.responseAddress=response.MSAXT_MSAXTALTSERVFXPD
