# context name

java.naming.factory.initial = org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory

#connectionfactory.connection = amqp://10.112.46.69:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN
connectionfactory.connection = amqp://otc-clearing-test-smoke3-secondary-rhel-01.clearing-otc.dev.gcp.dbgcloud.io:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

#queue.TradeNotification_VCON=VCON_Account1

#queue.requestAddess = request.MCAPI
#queue.responseAddress = ResponseQueue

# Broadcast Queues
#topic.TradeNotification_Bloomberg=broadcast/broadcast.BLOXT_BGLPRALBBFITPROD.TradeNotification
topic.TradeNotification_BLOOMBERG=broadcast/broadcast.BLOXT_BGLPRALBBFITPROD.TradeNotification





# Request Queues
queue.requestAddress_BLOXT_BGLPRALBBFITPROD=request_be.BLOXT_BGLPRALBBFITPROD


# Queue for viewing response on qpid broker UI
queue.responseAddress=response/response.BLOXT_BGLPRALBBFITPROD

# JMS Destination
queue.jmsDestination=eurex.fpml.request_be.BLOXT_BGLPRALBBFITPROD





