################################################################################ 
# 
#  MODULE NAME: FpmlAPIProperties.properties 
# 
#  DESCRIPTION: Contains the required property value to connect to FpML btoker
# 
#  MODIFICATION HISTORY 
# 
#    DATE      PROG. 
#  DD-MMM-YYYY INIT.   SIR    MODIFICATION DESCRIPTION 
#  ----------- ------- ------ -------------------------------------------------- 
#  30-OCT-2013 MASINHA 253590 Added property api.mc.enable
################################################################################
# context name


#local configuration

connectionfactory.connection=amqp://10.127.168.216:20001?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.user=guest

# Broadcast Queues:
topic.TradeNotificationNCM_bntfr_fixlkfoam=broadcast/broadcast.response.bntfr_fixlkfoam.TradeNotificationNCM
topic.TradeNotification_bntfr_fixlkfoam=brodcast/broadcast.bntfr_fixlkfoam.TradeNotification
topic.TradeNotificationNCM_bzwfr_clrmqalmmclr1=broadcast/broadcast.response.bzwfr_clrmqalmmclr1.TradeNotificationNCM
topic.TradeNotification_bzwfr_clrmqalmmclr1=brodcast/broadcast.bzwfr_clrmqalmmclr1.TradeNotification
topic.TradeNotificationNCM_cbkfr_mservmoprd=broadcast/broadcast.response.cbkfr_mservmoprd.TradeNotificationNCM
topic.TradeNotification_cbkfr_mservmoprd=brodcast/broadcast.cbkfr_mservmoprd.TradeNotification
topic.TradeNotificationNCM_cbkfr_sefxvmoprd=broadcast/broadcast.response.cbkfr_sefxvmoprd.TradeNotificationNCM
topic.TradeNotification_cbkfr_sefxvmoprd=brodcast/broadcast.cbkfr_sefxvmoprd.TradeNotification
topic.TradeNotificationNCM_csilo_cslnkfofpml=broadcast/broadcast.response.csilo_cslnkfofpml.TradeNotificationNCM
topic.TradeNotification_csilo_cslnkfofpml=brodcast/broadcast.csilo_cslnkfofpml.TradeNotification
topic.TradeNotificationNCM_dbkfr_dbsccfodtna1=broadcast/broadcast.response.dbkfr_dbsccfodtna1.TradeNotificationNCM
topic.TradeNotification_dbkfr_dbsccfodtna1=brodcast/broadcast.dbkfr_dbsccfodtna1.TradeNotification
topic.TradeNotificationNCM_dgefr_mservmoprd=broadcast/broadcast.response.dgefr_mservmoprd.TradeNotificationNCM
topic.TradeNotification_dgefr_mservmoprd=brodcast/broadcast.dgefr_mservmoprd.TradeNotification
topic.TradeNotificationNCM_dgzfr_mservmoprd=broadcast/broadcast.response.dgzfr_mservmoprd.TradeNotificationNCM
topic.TradeNotification_dgzfr_mservmoprd=brodcast/broadcast.dgzfr_mservmoprd.TradeNotification
topic.TradeNotificationNCM_gsieb_dcs_mbstpldnprod=broadcast/broadcast.response.gsieb_dcs_mbstpldnprod.TradeNotificationNCM
topic.TradeNotification_gsieb_dcs_mbstpldnprod=brodcast/broadcast.gsieb_dcs_mbstpldnprod.TradeNotification
topic.TradeNotificationNCM_jpofr_jpmcbboamcompprd=broadcast/broadcast.response.jpofr_jpmcbboamcompprd.TradeNotificationNCM
topic.TradeNotification_jpofr_jpmcbboamcompprd=brodcast/broadcast.jpofr_jpmcbboamcompprd.TradeNotification
topic.TradeNotificationNCM_jpofr_mservmoprd=broadcast/broadcast.response.jpofr_mservmoprd.TradeNotificationNCM
topic.TradeNotification_jpofr_mservmoprd=brodcast/broadcast.jpofr_mservmoprd.TradeNotification
topic.TradeNotificationNCM_lbwir_mservmoprd=broadcast/broadcast.response.lbwir_mservmoprd.TradeNotificationNCM
topic.TradeNotification_lbwir_mservmoprd=brodcast/broadcast.lbwir_mservmoprd.TradeNotification
topic.TradeNotificationNCM_lbymu_mservmoprd=broadcast/broadcast.response.lbymu_mservmoprd.TradeNotificationNCM
topic.TradeNotification_lbymu_mservmoprd=brodcast/broadcast.lbymu_mservmoprd.TradeNotification
topic.TradeNotificationNCM_mgilo_mgilobomq1=broadcast/broadcast.response.mgilo_mgilobomq1.TradeNotificationNCM
topic.TradeNotification_mgilo_mgilobomq1=brodcast/broadcast.mgilo_mgilobomq1.TradeNotification
topic.TradeNotificationNCM_sailo_otcprmboasystcny=broadcast/broadcast.response.sailo_otcprmboasystcny.TradeNotificationNCM
topic.TradeNotification_sailo_otcprmboasystcny=brodcast/broadcast.sailo_otcprmboasystcny.TradeNotification
topic.TradeNotificationNCM_sogcx_sogcxalammurex01=broadcast/broadcast.response.sogcx_sogcxalammurex01.TradeNotificationNCM
topic.TradeNotification_sogcx_sogcxalammurex01=brodcast/broadcast.sogcx_sogcxalammurex01.TradeNotification
topic.TradeNotificationNCM_sogcx_xxonealparis=broadcast/broadcast.response.sogcx_xxonealparis.TradeNotificationNCM
topic.TradeNotification_sogcx_xxonealparis=brodcast/broadcast.sogcx_xxonealparis.TradeNotification
topic.TradeNotificationNCM_zkbzh_mservmoprd=broadcast/broadcast.response.zkbzh_mservmoprd.TradeNotificationNCM
topic.TradeNotification_zkbzh_mservmoprd=brodcast/broadcast.zkbzh_mservmoprd.TradeNotification

topic.TradeNotificationNCM_BASBA_Account1=broadcast/broadcast.response.BASBA_Account1.TradeNotificationNCM
topic.TradeNotification_BASBA_Account1=brodcast/broadcast.BASBA_Account1.TradeNotification
topic.TradeNotificationNCM_KBBBE_Account1=broadcast/broadcast.response.KBBBE_Account1.TradeNotificationNCM
topic.TradeNotification_KBBBE_Account1=brodcast/broadcast.KBBBE_Account1.TradeNotification
topic.TradeNotificationNCM_ZKBZH_Account1=broadcast/broadcast.response.ZKBZH_Account1.TradeNotificationNCM
topic.TradeNotification_ZKBZH_Account1=brodcast/broadcast.ZKBZH_Account1.TradeNotification

#topic.TradeNotificationNCM_CBKFR=broadcast/broadcast.response.CBKFR.TradeNotificationNCM
#topic.TradeNotification_CBKFR=brodcast/broadcast.CBKFR.TradeNotification


#topic.TradeNotificationNCM_ARLIR=response.ARLIR.TradeNotificationNCM
#topic.TradeNotification_ARLIR=ARLIR.TradeNotification
#topic.TradeNotificationNCM_AACLU=response.AACLU.TradeNotificationNCM
#topic.TradeNotification_AACLU=AACLU.TradeNotification

#topic.TradeNotificationNCM_DBKFR=response.DBKFR.TradeNotificationNCM
#topic.TradeNotification_DBKFR=DBKFR.TradeNotification


# Request Queues
queue.requestAddress_bntfr_fixlkfoam=request_be.bntfr_fixlkfoam
queue.requestAddress_bzwfr_clrmqalmmclr1=request_be.bzwfr_clrmqalmmclr1
queue.requestAddress_cbkfr_mservmoprd=request_be.cbkfr_mservmoprd
queue.requestAddress_cbkfr_sefxvmoprd=request_be.cbkfr_sefxvmoprd
queue.requestAddress_csilo_cslnkfofpml=request_be.csilo_cslnkfofpml
queue.requestAddress_dbkfr_dbsccfodtna1=request_be.dbkfr_dbsccfodtna1
queue.requestAddress_dgefr_mservmoprd=request_be.dgefr_mservmoprd
queue.requestAddress_dgzfr_mservmoprd=request_be.dgzfr_mservmoprd
queue.requestAddress_gsieb_dcs_mbstpldnprod=request_be.gsieb_dcs_mbstpldnprod
queue.requestAddress_jpofr_jpmcbboamcompprd=request_be.jpofr_jpmcbboamcompprd
queue.requestAddress_jpofr_mservmoprd=request_be.jpofr_mservmoprd
queue.requestAddress_lbwir_mservmoprd=request_be.lbwir_mservmoprd
queue.requestAddress_lbymu_mservmoprd=request_be.lbymu_mservmoprd
queue.requestAddress_mgilo_mgilobomq1=request_be.mgilo_mgilobomq1
queue.requestAddress_sailo_otcprmboasystcny=request_be.sailo_otcprmboasystcny
queue.requestAddress_sogcx_sogcxalammurex01=request_be.sogcx_sogcxalammurex01
queue.requestAddress_sogcx_xxonealparis=request_be.sogcx_xxonealparis
queue.requestAddress_zkbzh_mservmoprd=request_be.zkbzh_mservmoprd

queue.requestAddress_BASBA_Account1=request_be.BASBA_Account1
queue.requestAddress_KBBBE_Account1=request_be.KBBBE_Account1
queue.requestAddress_ZKBZH_Account1=request_be.ZKBZH_Account1

#queue.requestAddress_CBKFR=eurex.fpml.request.CBKFR

#queue.requestAddress_ARLIR=request.ARLIR


queue.responseAddress=response.cbkfr_mservmoprd

api.mc.enable=