################################################################################ 
# 
#  MODULE NAME: marginCalcAPI.properties 
# 
#  DESCRIPTION: Contains the required property value for margin calculator to
#               connect to API btoker
# 
#  MODIFICATION HISTORY 
# 
#    DATE      PROG. 
#  DD-MMM-YYYY INIT.   SIR    MODIFICATION DESCRIPTION 
#  ----------- ------- ------ -------------------------------------------------- 
#  13-FEB-2014 PATHVIM 256187 Created   IRS: Relocate Margin Calculator API to ERS
#                                       channel 
################################################################################

# context name
java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jndi.PropertiesFileInitialContextFactory

connectionfactory.connection=amqp://10.112.47.73:20003?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

#queue.requestAddesss=request.MCAPI
#queue.responseAddress=response.ResponseQueue


queue.requestAddress_dbkfr_dbkfrfoamkanprd1=request_be.dbkfr_dbkfrfoamkanprd1
queue.requestAddress_bntfr_dvsimfoamprd=request_be.bntfr_dvsimfoamprd
queue.requestAddress_bntfr_dvsimfoamstg=request_be.bntfr_dvsimfoamstg
queue.requestAddress_boslo_produfoaaoptimus=request_be.boslo_produfoaaoptimus
queue.requestAddress_jpofr_omrgnalotccprod=request_be.jpofr_omrgnalotccprod
queue.requestAddress_sailo_margincalcclr001=request_be.sailo_margincalcclr001
queue.requestAddress_sogcx_sogcxalahmadn=request_be.sogcx_sogcxalahmadn
queue.requestAddress_sogcx_sogcxalandrea=request_be.sogcx_sogcxalandrea

queue.requestAddress_CSILO_Account1_MCAPI=request_be.CSILO_Account1_MCAPI
queue.requestAddress_CBKFR_CBKFRCLR001=request_be.CBKFR_CBKFRCLR001
queue.requestAddress_DGZFR_Account1_MCAPI=request_be.DGZFR_Account1_MCAPI
queue.requestAddress_BASBA_Account1_MCAPI=request_be.BASBA_Account1_MCAPI
queue.requestAddress_BZWFR_Account1_MCAPI=request_be.BZWFR_Account1_MCAPI
queue.requestAddress_KBBBE_Account1_MCAPI=request_be.KBBBE_Account1_MCAPI
queue.requestAddress_ZKBZH_Account1_MCAPI=request_be.ZKBZH_Account1_MCAPI


api.mc.enable=true
