# context name

java.naming.factory.initial = org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory

#connectionfactory.connection = amqp://10.112.46.69:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN
connectionfactory.connection = amqp://10.112.47.73:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

#connectionfactory.connection = amqp://10.112.47.73:20002?jms.username=amqpsrv&jms.password=12345678&amqp.saslMechanisms=PLAIN


#queue.TradeNotification_VCON=VCON_Account1

# Broadcast Queues
topic.TradeNotification_Bloomberg=brodcast/broadcast.BLOXT_BGLPRALBBFITPROD.TradeNotification
topic.TradeNotification_MISXT=brodcast/broadcast.MISXT_TEAPIMOPRD.TradeNotification
topic.TradeNotification_MISXT=brodcast/broadcast.MSAXT_MSAXTALTSERVFXPD.TradeNotification
topic.TradeNotification_TRIANA=brodcast/broadcast.TRAXT_TRAXTALNDFPROD.TradeNotification
topic.TradeNotification_TRIANA=brodcast/broadcast.TRAXT_TRAXTALTEAPROD.TradeNotification
topic.TradeNotification_360T=brodcast/broadcast.TSTXT_360TFX1.TradeNotification
topic.TradeNotification_TradeWeb=brodcast/broadcast.TWBXT_TWEB1FOAAPRODCLR.TradeNotification
topic.TradeNotification_TradeWeb=brodcast/broadcast.TWBXT_TWEB2FOAAPRODCLR.TradeNotification

#topic.TradeNotification_Bloomberg=brodcast/broadcast.BLOXT_BGLPRALBBFITPROD1.TradeNotification
#topic.TradeNotification_Bloomberg=brodcast/broadcast.BLOXT_BGLPRALBBFITPROD2.TradeNotification
#topic.TradeNotification_Bloomberg=brodcast/broadcast.BLOXT_BGLPRALBBFITPROD3.TradeNotification


# Request Queues                       
queue.requestAddress_BLOXT_BGLPRALBBFITPROD=request_be.BLOXT_BGLPRALBBFITPROD
queue.requestAddress_MISXT_TEAPIMOPRD=request_be.MISXT_TEAPIMOPRD
queue.requestAddress_MSAXT_MSAXTALTSERVFXPD=request_be.MSAXT_MSAXTALTSERVFXPD
queue.requestAddress_TRAXT_TRAXTALNDFPROD=request_be.TRAXT_TRAXTALNDFPROD
queue.requestAddress_TRAXT_TRAXTALTEAPROD=request_be.TRAXT_TRAXTALTEAPROD
queue.requestAddress_TSTXT_360TFX1=request_be.TSTXT_360TFX1
queue.requestAddress_TWBXT_TWEB1FOAAPRODCLR=request_be.TWBXT_TWEB1FOAAPRODCLR
queue.requestAddress_TWBXT_TWEB2FOAAPRODCLR=request_be.TWBXT_TWEB2FOAAPRODCLR

#queue.requestAddress_BLOXT_BGLPRALBBFITPROD1=eurex.fpml.request.BLOXT_BGLPRALBBFITPROD1
#queue.requestAddress_BLOXT_BGLPRALBBFITPROD2=eurex_request_test.BLOXT_BGLPRALBBFITPROD2
#queue.requestAddress_BLOXT_BGLPRALBBFITPROD3=request.BLOXT_BGLPRALBBFITPROD3

queue.requestAddressMWNETAmendment=request_be.MWNETA

# Queue for viewing response on qpid broker UI

queue.responseAddress=response.MWNETA
queue.responseAddress=response.BLOXT_BGLPRALBBFITDEV
queue.responseAddress=response.MISXT_TEAPIMOPRD
queue.responseAddress=response.MSAXT_MSAXTALTSERVFXPD
queue.responseAddress=response.TRAXT_TRAXTALNDFPROD
queue.responseAddress=response.TRAXT_TRAXTALTEAPROD
queue.responseAddress=response.TSTXT_360TFX1
queue.responseAddress=response.TWBXT_TWEB1FOAAPRODCLR
queue.responseAddress=response.TWBXT_TWEB2FOAAPRODCLR

