## Url should be as per new convention
java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jndi.PropertiesFileInitialContextFactory

## Url should be as per new convention
connectionfactory.qpidConnectionfactory=amqp://otc-clearing-test-smoke2-secondary-rhel-01.clearing-otc.dev.gcp.dbgcloud.io:20004?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN
connectionfactory.connection=amqp://otc-clearing-test-smoke2-secondary-rhel-01.clearing-otc.dev.gcp.dbgcloud.io:20004?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

queue.requestAddress= request_be.EUREX_EUREXALMMWEBAPP
#queue.responseAddress=ResponseQueue
jms.user=default
