# context name

java.naming.factory.initial = org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory

#connectionfactory.connection = amqp://10.112.46.69:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN
connectionfactory.connection = amqp://10.112.36.222:20002?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

#queue.TradeNotification_VCON=VCON_Account1
topic.TradeNotification_BLOOMBERG=broadcastTEAPI/broadcastTEAPI.BLOOMBERG
topic.TradeNotification_TRADEWEB=broadcastTEAPI/broadcastTEAPI.TRADEWEB
topic.TradeNotification_TRAIANA=broadcastTEAPI/broadcastTEAPI.TRAIANA
topic.TradeNotification_360T=broadcastTEAPI/broadcastTEAPI.360T

queue.requestAddress_BLOOMBERG=request_be.BLOOMBERG
queue.requestAddress_TradeWeb=request_be.TRADEWEB
queue.requestAddress_TRAIANA=request_be.TRAIANA
queue.requestAddress_360T=request_be.360T
queue.requestAddress_BLOXT=request_be.BLOXT_BGLPRALBBFITDEV

queue.requestAddressMWNETAmendment=request_be.MWNETA



queue.responseAddress=response.MWNETA
queue.responseAddress=response.BLOXT_BGLPRALBBFITDEV