################################################################################ 
# 
#  MODULE NAME: FpmlAPIProperties.properties 
# 
#  DESCRIPTION: Contains the required property value to connect to FpML btoker
# 
#  MODIFICATION HISTORY 
# 
#    DATE      PROG. 
#  DD-MMM-YYYY INIT.   SIR    MODIFICATION DESCRIPTION 
#  ----------- ------- ------ -------------------------------------------------- 
#  30-OCT-2013 MASINHA 253590 Added property api.mc.enable
################################################################################
# context name


#local configuration

connectionfactory.connection=amqp://10.127.168.147:20001?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.user=guest

# Broadcast Queues:
topic.TradeNotificationNCM_SOGCX_SOGCXALAMMUREX01=broadcast/broadcast.SOGCX_SOGCXALAMMUREX01.TradeNotificationNCM
topic.TradeNotification_SOGCX_SOGCXALAMMUREX01=brodcast/broadcast.SOGCX_SOGCXALAMMUREX01.TradeNotification

# Request Queues
queue.requestAddress_SOGCX_SOGCXALAMMUREX01=request_be.SOGCX_SOGCXALAMMUREX01

# Response Queue
queue.responseAddress=response.SOGCX_SOGCXALAMMUREX01

api.mc.enable=