################################################################################ 
# 
#  MODULE NAME: FpmlAPIProperties.properties 
# 
#  DESCRIPTION: Contains the required property value to connect to FpML btoker
# 
#  MODIFICATION HISTORY 
# 
#    DATE      PROG. 
#  DD-MMM-YYYY INIT.   SIR    MODIFICATION DESCRIPTION 
#  ----------- ------- ------ -------------------------------------------------- 
#  30-OCT-2013 MASINHA 253590 Added property api.mc.enable
################################################################################
# context name


#local configuration

connectionfactory.connection=amqp://10.127.168.147:20001?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.user=guest

# Broadcast Queues:
topic.TradeNotificationNCM_CSILO_CSLNKFOFPML=broadcast/broadcast.CSILO_CSLNKFOFPML.TradeNotificationNCM
topic.TradeNotification_CSILO_CSLNKFOFPML=brodcast/broadcast.CSILO_CSLNKFOFPML.TradeNotification

# Request Queues
queue.requestAddress_CSILO_CSLNKFOFPML=request_be.CSILO_CSLNKFOFPML

#Reponse Queue
queue.responseAddress=response.CSILO_CSLNKFOFPML

api.mc.enable=