################################################################################ 
# 
#  MODULE NAME: FpmlAPIProperties.properties 
# 
#  DESCRIPTION: Contains the required property value to connect to FpML btoker
# 
#  MODIFICATION HISTORY 
# 
#    DATE      PROG. 
#  DD-MMM-YYYY INIT.   SIR    MODIFICATION DESCRIPTION 
#  ----------- ------- ------ -------------------------------------------------- 
#  30-OCT-2013 MASINHA 253590 Added property api.mc.enable
################################################################################
# context name


#local configuration

connectionfactory.connection=amqp://10.127.168.147:20001?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.user=guest

# Broadcast Queues:
topic.TradeNotificationNCM_CBKFR_MSERVMOPRD=broadcast/broadcast.CBKFR_MSERVMOPRD.TradeNotificationNCM
topic.TradeNotification_CBKFR_MSERVMOPRD=brodcast/broadcast.CBKFR_MSERVMOPRD.TradeNotification

# Request Queues
queue.requestAddress_CBKFR_MSERVMOPRD=request_be.CBKFR_MSERVMOPRD

# sat test
#queue.requestAddress_CBKFR_MSERVMOPRD1=request.CBKFR_MSERVMOPRD1

#Response Queue
queue.responseAddress=response.CBKFR_MSERVMOPRD
#queue.responseAddress=response.CBKFR_MSERVMOPRD1

api.mc.enable=

# JMS Destination
# sat test
#queue.jmsDestination=eurex.fpml.request_be.CBKFR_MSERVMOPRD1