################################################################################ 
# 
#  MODULE NAME: FpmlAPIProperties.properties 
# 
#  DESCRIPTION: Contains the required property value to connect to FpML btoker
# 
#  MODIFICATION HISTORY 
# 
#    DATE      PROG. 
#  DD-MMM-YYYY INIT.   SIR    MODIFICATION DESCRIPTION 
#  ----------- ------- ------ -------------------------------------------------- 
#  30-OCT-2013 MASINHA 253590 Added property api.mc.enable
################################################################################
# context name


#local configuration

connectionfactory.connection=amqp://10.127.168.147:20001?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.modetypeclass=org.apache.qpid.jms.jndi.JmsInitialContextFactory
jms.user=guest

# Broadcast Queues:

topic.TradeNotificationNCM_CBKFR_SEFXVMOPRD=broadcast/broadcast.CBKFR_SEFXVMOPRD.TradeNotificationNCM
topic.TradeNotification_CBKFR_SEFXVMOPRD=brodcast/broadcast.CBKFR_SEFXVMOPRD.TradeNotification

# Request Queues
queue.requestAddress_CBKFR_SEFXVMOPRD=request_be.CBKFR_SEFXVMOPRD

#Response Queue
queue.responseAddress=response.CBKFR_SEFXVMOPRD

api.mc.enable=