################################################################################
#
#  MODULE NAME: marginCalc.properties
#
#  DESCRIPTION: Contains the required property value for margin calculator to
#               connect to GUI btoker
#
#  MODIFICATION HISTORY
#
#    DATE      PROG.
#  DD-MMM-YYYY INIT.   SIR    MODIFICATION DESCRIPTION
#  ----------- ------- ------ --------------------------------------------------
#  30-OCT-2013 MASINHA 253590 Added property gui.mc.enable
################################################################################

# context name
java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory

#local configuration
connectionfactory.qpidConnectionfactory=amqp://10.127.168.147:20004?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN
connectionfactory.connection=amqp://10.127.168.147:20004?jms.username=admin&jms.password=admin&amqp.saslMechanisms=PLAIN

#queue.requestAddress.calypso=GUI.MC
queue.requestAddress=request_be.EUREX_MARGINCALC
queue.responseAddress=ResponseQueue
gui.mc.enable=true

